<?php

namespace Nalys\SkillsmappingBundle\Repository;

/**
 * MissionSkillRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MissionSkillRepository extends \Doctrine\ORM\EntityRepository
{
}
