<?php

namespace Nalys\SkillsmappingBundle\Repository;

/**
 * UserSkillRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserSkillRepository extends \Doctrine\ORM\EntityRepository
{
}
