<?php

namespace Nalys\MissionsmappingBundle\Repository;

/**
 * UserMissionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserMissionRepository extends \Doctrine\ORM\EntityRepository
{
}
