nalys_skillsmapping:
    resource: "@NalysSkillsmappingBundle/Resources/config/routing.yml"
    prefix:   /

skillsmapping_api:
    type: rest
    prefix: /api
    resource: "@NalysSkillsmappingBundle/Resources/config/api-routing.yml"

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc

fos_oauth_server_token:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"

fos_oauth_server_authorize:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/authorize.xml"

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
